# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='describe',
            new_name='description',
        ),
    ]
