# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='类别')),
                ('date_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-date_time'],
            },
        ),
    ]
